# Generated by Django 2.0.7 on 2018-10-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollnumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
