# Generated by Django 2.0.5 on 2018-10-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=25)),
                ('branch_code', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('branch_name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=45)),
                ('course_code', models.CharField(max_length=7)),
                ('attendance', models.PositiveIntegerField()),
                ('branch', models.ManyToManyField(to='sis.Branch')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('C', 'C'), ('D', 'D'), ('P', 'P')], max_length=2)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sis.Course')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=10)),
                ('semester_code', models.CharField(max_length=2)),
                ('branch', models.ManyToManyField(to='sis.Branch')),
            ],
            options={
                'ordering': ('semester_code',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Branch')),
                ('courses', models.ManyToManyField(to='sis.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sis.Semester'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sis.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Semester'),
        ),
    ]
