# Generated by Django 2.0.7 on 2018-10-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
    ]
