# Generated by Django 2.0.5 on 2018-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_auto_20181002_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attendance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
