# Generated by Django 2.0.7 on 2018-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_remove_semester_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
    ]
