# Generated by Django 2.0.7 on 2018-10-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_auto_20181012_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
