# Generated by Django 2.0.7 on 2018-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0004_auto_20181012_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('C', 'C'), ('D', 'D'), ('P', 'P'), ('Absent', 'Absent')], max_length=10),
        ),
    ]
