# Generated by Django 2.0.7 on 2018-10-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20181012_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
