# Generated by Django 2.0.7 on 2018-10-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_branch_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('HOD', 'HOD')], max_length=50),
        ),
    ]
