# Generated by Django 2.0.7 on 2018-10-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0006_auto_20181009_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='address1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pob',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
