# Generated by Django 2.0.7 on 2018-10-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_marklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='marklist',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.Semester'),
        ),
    ]
