# Generated by Django 2.0.7 on 2018-10-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20181009_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
