# Generated by Django 2.0.7 on 2018-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_auto_20181009_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_slug',
            field=models.SlugField(max_length=25, null=True),
        ),
    ]
