# Generated by Django 2.0.7 on 2018-10-09 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_customuser_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
