# Generated by Django 2.0.7 on 2018-10-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0010_auto_20181013_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marklist',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Semester'),
        ),
    ]
