# Generated by Django 2.0.7 on 2018-10-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_auto_20181013_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('HOD', 'HOD')], default='STUDENT', max_length=50),
        ),
    ]
