# Generated by Django 2.0.7 on 2018-10-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_auto_20181013_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
    ]
