# Generated by Django 2.0.7 on 2018-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0013_remove_exam_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
