# Generated by Django 2.0.7 on 2018-10-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0015_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ('-time',)},
        ),
    ]
