# Generated by Django 2.0.7 on 2018-10-17 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0018_auto_20181017_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='rise_message',
        ),
        migrations.AddField(
            model_name='pot',
            name='riser_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
