# Generated by Django 2.0.7 on 2018-10-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0019_auto_20181017_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pot',
            name='dipper',
        ),
        migrations.DeleteModel(
            name='Pot',
        ),
    ]
